Merge-RELEASE. Project 2. #1. Week 12
saffchen/JRM-Java-Stock-System pull request #108
Opened 2022-11-07 15:09 UTC by saffchen

2022-11-07 15:40 UTC, pelmegov requested changes

2022-11-07 15:40 UTC, pelmegov commented on stock/src/main/java/saffchen/service/StoreService.java
> +        return storeRepository.findByName(storeName).get();
NPE?

2022-11-07 15:40 UTC, pelmegov commented on stock/src/main/java/saffchen/repository/ProductRepository.java
> +    /*@Query(value = "select p from ProductEntity p where p.store.id = :storeId")
Remove unused code.

2022-11-07 15:40 UTC, pelmegov commented on stock/src/main/java/saffchen/repository/ProductRepository.java
> +    Optional<ProductEntity> get(Long storeId,Long id);
Autoformatting.

2022-11-07 15:40 UTC, pelmegov commented on stock/src/main/java/saffchen/mapper/ProductMapper.java
> +    @Mapping(source = "store.name", target = "storeName")
Change is supported by frontend?

2022-11-07 15:40 UTC, pelmegov commented on stock/src/main/java/saffchen/entities/ProductEntity.java
>      //@JoinColumn(name = "satelliteId", referencedColumnName = "id")
Unused code should be deleted.

2022-11-07 15:40 UTC, pelmegov commented on stock/src/main/java/saffchen/config/SecurityConfig.java
> +                //.mvcMatchers(HttpMethod.PUT,"/api/v1/admin/**").hasAuthority("ROLE_ADMIN")
Unused code should be removed.

2022-11-07 15:40 UTC, pelmegov commented on report/src/main/java/saffchen/reports/SwitchTheme.java
> +public class SwitchTheme {
This switcher doesn't switch anything, it's better to have one method and switch the theme by requested color.

2022-11-07 15:40 UTC, pelmegov commented on report/src/main/java/saffchen/reports/LightThemePDF.java
> +        return theme.getBaseColor(BaseColor.WHITE);
Does it return the same value? Like BaseColor.WHITE? If so why do we need theme here?

2022-11-07 17:53 UTC, saffchen commented on stock/src/main/java/saffchen/repository/ProductRepository.java
> +    Optional<ProductEntity> get(Long storeId,Long id);
Fixed

2022-11-07 17:56 UTC, saffchen commented on stock/src/main/java/saffchen/entities/ProductEntity.java
>      //@JoinColumn(name = "satelliteId", referencedColumnName = "id")
Fixed

2022-11-07 17:57 UTC, saffchen commented on stock/src/main/java/saffchen/config/SecurityConfig.java
> +                //.mvcMatchers(HttpMethod.PUT,"/api/v1/admin/**").hasAuthority("ROLE_ADMIN")
Fixed

2022-11-08 21:49 UTC, aalexeen commented on stock/src/main/java/saffchen/mapper/ProductMapper.java
> +    @Mapping(source = "store.name", target = "storeName")
I've done it a long time ago. The frontend was working.

2022-11-09 15:43 UTC, aalexeen commented on import/src/main/java/saffchen/command/Command.java
> +
Just simple refactoring

2022-11-09 17:22 UTC, saffchen commented on stock/src/main/java/saffchen/repository/ProductRepository.java
> +    /*@Query(value = "select p from ProductEntity p where p.store.id = :storeId")
Fixed

2022-11-09 21:31 UTC, aalexeen commented on stock/src/main/java/saffchen/service/StoreService.java
> +        return storeRepository.findByName(storeName).get();
Fixed

2022-11-14 14:27 UTC, aalexeen approved these changes

2022-11-16 20:11 UTC, pelmegov approved these changes

2022-11-17 05:00 UTC, merged