Dev
saffchen/JRM-Java-Stock-System pull request #20
Opened 2022-05-16 18:00 UTC by saffchen

Sprint 1

2022-05-16 18:35 UTC, pelmegov commented on stock-system/src/main/java/saffchen/MenuRunner.java
> +        holder.addCommand("EXIT", new ExitCommand());
This is a static information, in theory we can make this preparation of map separately, extracting it from this place, what do you think?

2022-05-16 18:37 UTC, pelmegov commented on stock-system/src/main/java/saffchen/MenuRunner.java
> +                String inputCommand = new Scanner(System.in).next().trim().toUpperCase();
Can we create scanner just once? It can reduce performance impact.

2022-05-16 18:38 UTC, pelmegov commented on stock-system/src/main/java/saffchen/MenuRunner.java
> +                System.out.println("Unsupported operation. Try again.");
This unsupported operation should be shown when user input is incorrect, right? But for now the logic is incorrect.

2022-05-16 18:40 UTC, pelmegov commented on stock-system/src/main/java/saffchen/command/AddCommand.java
> +        database.add_product(product);
Please use Java Naming Conventions for method names: https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html

2022-05-16 18:41 UTC, pelmegov commented on stock-system/src/main/java/saffchen/command/Command.java
> +    public void doCommand();
Interface's methods public by default.

2022-05-16 18:41 UTC, pelmegov commented on stock-system/src/main/java/saffchen/command/CommandHolder.java
> +    private Map<String, Command> commandHolder = new HashMap<>();
Let's keep the fields under the methods. The map also can be final.

2022-05-16 18:42 UTC, pelmegov commented on stock-system/src/main/java/saffchen/command/CommandHolder.java
> +        }catch (Exception e){
Can you little bit elaborate when this exception could be thrown?

2022-05-16 18:43 UTC, pelmegov commented on stock-system/src/main/java/saffchen/command/DeleteCommand.java
> +        database.delete_product();
The same, method naming should be fixed .

2022-05-16 18:46 UTC, pelmegov commented on stock-system/src/main/java/saffchen/greeting_message/GreetingMessage.java
> +    private List<String> listOfMessages = Arrays.asList("Welcome to the Stock System",
I have a suggestion here. 
It's not easy to modify command and welcome message in different places.
Can we use our map with commands and iterating through this map show the message with command description? 

So, the command interface can have some required method like "String getDescription()", and every command will require to show itself description.

2022-05-16 18:47 UTC, pelmegov commented on stock-system/src/main/java/saffchen/product/Product.java
> +    public Product(){
Suggestion: 
What do you think about Lombok? Can we use it? Let's take a look with team.

2022-05-16 19:20 UTC, pelmegov requested changes

2022-05-16 19:20 UTC, pelmegov commented on participants.txt
> -rusokolov4@gmail.com - rusokolov1987
Do we have only 2 devs for now?

2022-05-16 19:20 UTC, pelmegov commented on stock-system/src/main/java/saffchen/utils/FileUtils.java
> +    public String getBanner(){
Those methods can be static, because this is Utility class.

2022-05-17 05:34 UTC, freesky15 commented on stock-system/src/main/java/saffchen/MenuRunner.java
> +                String inputCommand = new Scanner(System.in).next().trim().toUpperCase();
I agree with you. Done!

2022-05-17 05:39 UTC, freesky15 commented on stock-system/src/main/java/saffchen/MenuRunner.java
> +                System.out.println("Unsupported operation. Try again.");
Done!

2022-05-17 07:45 UTC, freesky15 commented on stock-system/src/main/java/saffchen/utils/FileUtils.java
> +    public String getBanner(){
Done!

2022-05-17 07:50 UTC, freesky15 commented on stock-system/src/main/java/saffchen/product/Product.java
> +    public Product(){
Maybe but I did'n deep into this scope. 
Possible, I'll deep into it a bit later

2022-05-17 07:52 UTC, freesky15 commented on stock-system/src/main/java/saffchen/command/DeleteCommand.java
> +        database.delete_product();
Done!

2022-05-17 08:00 UTC, freesky15 commented on stock-system/src/main/java/saffchen/command/CommandHolder.java
> +    private Map<String, Command> commandHolder = new HashMap<>();
Done!

2022-05-17 08:00 UTC, freesky15 commented on stock-system/src/main/java/saffchen/command/AddCommand.java
> +        database.add_product(product);
Done!

2022-05-17 08:06 UTC, freesky15 commented on stock-system/src/main/java/saffchen/MenuRunner.java
> +            }catch(Exception e){
What do you mean? I can't understand )

2022-05-17 08:25 UTC, pelmegov commented on stock-system/src/main/java/saffchen/product/Product.java
> +    public Product(){
No worries, if you want to exclude it from this release, that's okay.

2022-05-17 08:26 UTC, pelmegov commented on stock-system/src/main/java/saffchen/utils/FileUtils.java
> +    public String getBanner(){
@freesky15 you are putting Done comment, but I don't see any new commits in the PR. Can you please explain me where the changes are done?

2022-05-17 08:43 UTC, freesky15 commented on stock-system/src/main/java/saffchen/utils/FileUtils.java
> +    public String getBanner(){
Just a moment. I will fix all suggestions and will commit these

2022-05-17 08:51 UTC, freesky15 commented on stock-system/src/main/java/saffchen/command/Command.java
> +    public void doCommand();
Done!

2022-05-17 08:55 UTC, freesky15 commented on stock-system/src/main/java/saffchen/command/CommandHolder.java
> +        }catch (Exception e){
or null is correct value as a hashmap key?

2022-05-17 09:03 UTC, freesky15 commented on stock-system/src/main/java/saffchen/MenuRunner.java
> +        holder.addCommand("EXIT", new ExitCommand());
I move it to CommandHolder method calls getPreparedCommandHolder

2022-05-17 09:15 UTC, freesky15 commented on stock-system/src/main/java/saffchen/utils/FileUtils.java
> +    public String getBanner(){
I fixed suggestions and pushed it to the add_Pdf_report branch

2022-05-17 09:22 UTC, freesky15 commented on stock-system/src/main/java/saffchen/greeting_message/GreetingMessage.java
> +    private List<String> listOfMessages = Arrays.asList("Welcome to the Stock System",
I suggest with you. I'll think about it and I'll realize it

2022-05-17 11:17 UTC, freesky15 commented on stock-system/src/main/java/saffchen/MenuRunner.java
> +            }catch(Exception e){
Done!

2022-05-17 15:22 UTC, pelmegov commented on stock-system/src/main/java/saffchen/utils/FileUtils.java
> +    public String getBanner(){
@freesky15 Please make changes in this PR, because we are reviewing this one. 
cc @saffchen

2022-05-17 17:21 UTC, pelmegov approved these changes

2022-05-17 17:30 UTC, merged