Merge-RELEASE #2. Week 2.
saffchen/JRM-Java-Stock-System pull request #28
Opened 2022-05-21 15:11 UTC by saffchen

Create: 
1. Generate report
2. Export excel

2022-05-21 15:35 UTC, pelmegov requested changes

2022-05-21 15:35 UTC, pelmegov commented on stock-system/pom.xml
> +            <dependency>
Let's use autoformatting.

2022-05-21 15:35 UTC, pelmegov commented on stock-system/pom.xml
> +            <version>5.6</version>
It is better to move versions under properties, can we do that?

2022-05-21 15:35 UTC, pelmegov commented on stock-system/src/main/java/saffchen/command/CreateXlsFileCommand.java
> +        receiverDB.createXLS();
Database should not have method createXLS because it is not database responsibility. Database can return required data and that's it.

2022-05-21 15:35 UTC, pelmegov commented on stock-system/src/main/java/saffchen/command/ReceiverDB.java
> +        while (name.contains("?") || name.contains("/") || name.contains(":") || name.contains("*") ||
Let's specify deprecated symbols in the List or Array, and then you can just iterate and check if the name contains one of deprecated symbols.

2022-05-21 15:35 UTC, pelmegov commented on stock-system/src/main/java/saffchen/command/ReceiverDB.java
> +    // Сформировать .xls отчет
This is comment for comment, you don't need to put comment if it does not introduce more clarification or information.

2022-05-21 15:35 UTC, pelmegov commented on stock-system/src/main/java/saffchen/command/ReceiverDB.java
>      public void createReport() {
This method is not part of DB class.

2022-05-21 15:35 UTC, pelmegov commented on stock-system/src/main/java/saffchen/database/DBConnection.java
> +        if (instance == null) {
It is okay if you wanna use singleton, but, you just have to care about its thread safety.

2022-05-21 15:35 UTC, pelmegov commented on stock-system/src/main/java/saffchen/reports/IReport.java
> +interface IReport {
This is pretty old practice to use "I" prefix, you can do it, if you want, but in current projects we usually specify the name of interface, without suffixes and prefixes.

2022-05-21 15:35 UTC, pelmegov commented on stock-system/src/main/java/saffchen/reports/PDFReportFromFileBySatellite.java
> +    ;
What does this semicolon here?

2022-05-21 15:35 UTC, pelmegov commented on stock-system/src/main/java/saffchen/reports/PDFReportFromFileBySatellite.java
> +            List<String> headers = Arrays.asList("TITLE", "DESCRIPTION", "PRICE", "TAGS", "CATEGORY", "COUNT", "SATELLITE");
Can be static.

2022-05-21 15:35 UTC, pelmegov commented on stock-system/src/main/java/saffchen/reports/PDFReportFromFileBySatellite.java
> +            boolean isLight = true; //if background is light
Can it be modifiable outside? If I want to change background in the runtime.

2022-05-21 15:35 UTC, pelmegov commented on stock-system/src/main/java/saffchen/utils/FileStorageUtils.java
> +        try {
You can use UnsupportedOperationException in similar scenarios, but this is also okay.

2022-05-21 15:35 UTC, pelmegov commented on stock-system/src/main/java/saffchen/utils/IStorageUtils.java
> +    IConnection I_CONNECTION = null;
What is the reason to have this null variable here?

2022-05-21 15:37 UTC, pelmegov commented
Guys, please also use understandable and describable commit messages, because sometimes it is complicated to understand what did you change.

2022-05-21 16:31 UTC, saffchen commented on stock-system/pom.xml
> +            <version>5.6</version>
Done!

2022-05-21 16:43 UTC, saffchen commented on stock-system/src/main/java/saffchen/reports/IReport.java
> +interface IReport {
Done!

2022-05-21 16:44 UTC, saffchen commented on stock-system/src/main/java/saffchen/reports/PDFReportFromFileBySatellite.java
> +    ;
Wrongly.
Fixed!

2022-05-21 16:45 UTC, saffchen commented on stock-system/src/main/java/saffchen/utils/FileStorageUtils.java
> +        try {
Done!

2022-05-21 16:54 UTC, saffchen commented on stock-system/src/main/java/saffchen/command/CreateXlsFileCommand.java
> +        receiverDB.createXLS();
Fixed!

2022-05-21 17:31 UTC, saffchen commented on stock-system/src/main/java/saffchen/command/ReceiverDB.java
>      public void createReport() {
Fixed!

2022-05-21 17:42 UTC, pelmegov requested changes

2022-05-21 17:42 UTC, pelmegov commented on stock-system/pom.xml
> +            <version>5.5.13.3</version>
property?

2022-05-21 17:42 UTC, pelmegov commented on stock-system/pom.xml
> +            <version>2.0.0</version>
property?

2022-05-21 17:42 UTC, pelmegov commented on stock-system/src/main/java/saffchen/command/CreateXlsFileCommand.java
> +        String path = System.getProperty("user.home") + "\\Desktop\\" + name + ".xls";
Will it work on macos, linux? It is better to put generated report to the some of the project folders.

2022-05-21 17:42 UTC, pelmegov commented on stock-system/src/main/java/saffchen/command/CreateXlsFileCommand.java
> +        createXLS();
What is the reason to call only one method? Looks like the whole method can be right here.

2022-05-21 17:42 UTC, pelmegov commented on stock-system/src/main/java/saffchen/command/GenerateReportCommand.java
> +            if (criteria.equals("EXIT"))
We already have exit command, can we reuse it?

2022-05-21 17:42 UTC, pelmegov commented on stock-system/src/main/java/saffchen/command/GenerateReportCommand.java
> +                System.out.println("Error: Can't create the report! Try again!");
It is better to write some infromation about exception, root cause is important.

2022-05-21 17:42 UTC, pelmegov commented on stock-system/src/main/java/saffchen/command/GenerateReportCommand.java
> +        createReport();
The same case, method can be inlined.

2022-05-21 17:42 UTC, pelmegov commented on stock-system/src/main/java/saffchen/command/ReceiverDB.java
>  public class ReceiverDB {
I have a question about naming, what does Receiver mean? Is it better to use ProductDB for the name?

2022-05-21 17:42 UTC, pelmegov commented on stock-system/src/main/java/saffchen/utils/FileStorageUtils.java
> +        try {
Actually, you can just throw it, without catching.

2022-05-21 19:10 UTC, saffchen commented on stock-system/pom.xml
> +            <version>5.5.13.3</version>
Fixed!

2022-05-21 19:10 UTC, saffchen commented on stock-system/pom.xml
> +            <version>2.0.0</version>
Fixed!

2022-05-22 09:46 UTC, saffchen commented on stock-system/src/main/java/saffchen/command/CreateXlsFileCommand.java
> +        String path = System.getProperty("user.home") + "\\Desktop\\" + name + ".xls";
Fixed!

2022-05-22 21:34 UTC, aalexeen reviewed
Classes DBConnection, FileConnection, and PDFReportFromFileBySatellite don't implement appropriate interfaces.
Should be Report and Connection accordingly.

2022-05-23 18:29 UTC, saffchen commented on stock-system/src/main/java/saffchen/command/GenerateReportCommand.java
> +            if (criteria.equals("EXIT"))
These are different command. This command indicates the exit from the command, and the other indicates the closure of the application

2022-05-23 18:31 UTC, saffchen commented on stock-system/src/main/java/saffchen/command/ReceiverDB.java
> +    // Сформировать .xls отчет
Fixed!

2022-05-24 08:50 UTC, pelmegov commented
Guys, do you have a plan to complete this PR?

2022-05-24 20:05 UTC, saffchen commented on stock-system/src/main/java/saffchen/reports/PDFReportFromFileBySatellite.java
> +            List<String> headers = Arrays.asList("TITLE", "DESCRIPTION", "PRICE", "TAGS", "CATEGORY", "COUNT", "SATELLITE");
Fixed!

2022-05-25 10:43 UTC, freesky15 commented on stock-system/src/main/java/saffchen/command/GenerateReportCommand.java
> +            if (criteria.equals("EXIT"))
This exit is exit from submenu to the level up

2022-05-25 10:45 UTC, freesky15 commented on stock-system/src/main/java/saffchen/command/GenerateReportCommand.java
> +                System.out.println("Error: Can't create the report! Try again!");
What do you mean? Stacktrace? If yes, then it's unsecured.

2022-05-25 10:46 UTC, freesky15 commented on stock-system/src/main/java/saffchen/command/GenerateReportCommand.java
> +        createReport();
Done! Refactoring the class

2022-05-25 10:50 UTC, freesky15 commented on stock-system/src/main/java/saffchen/command/ReceiverDB.java
>  public class ReceiverDB {
By Design of Command pattern. Ok, I'll rename it ^))

2022-05-25 10:57 UTC, freesky15 commented on stock-system/src/main/java/saffchen/reports/PDFReportFromFileBySatellite.java
> +            List<String> headers = Arrays.asList("TITLE", "DESCRIPTION", "PRICE", "TAGS", "CATEGORY", "COUNT", "SATELLITE");
Fixed! These entities get dynamically

2022-05-25 11:52 UTC, pelmegov requested changes

2022-05-25 11:52 UTC, pelmegov commented on stock-system/src/main/java/saffchen/command/GenerateReportCommand.java
> +            if (criteria.equals("EXIT"))
I agree, but does it make sense to make it more reusable and reuse it here and in the future?

2022-05-25 11:52 UTC, pelmegov commented on stock-system/src/main/java/saffchen/command/GenerateReportCommand.java
> +                System.out.println("Error: Can't create the report! Try again!");
It's unsecured when we will use web, but when you are working in local environment it's okay. We also can hide the details with logging frameworks, which will be one of the next features. You can do it here or consider to transfer this functionality to future features.

2022-05-25 11:52 UTC, pelmegov commented on stock-system/pom.xml
> -        <!-- https://mvnrepository.com/artifact/org.apache.pdfbox/pdfbox -->
PDF dependency is no longer required?

2022-05-25 11:52 UTC, pelmegov commented on stock-system/src/main/java/saffchen/command/ImportFromGSheetCommand.java
> +        receiverDB.importFromGsheet();
Why receiverDB is responsible to import from gsheet? I guess it should make this command, isn't it?

2022-05-25 11:52 UTC, pelmegov commented on stock-system/src/main/java/saffchen/product/RawProduct.java
> +    public String toCSVString(String sep){
why do you need to duplicate those methods?

2022-05-25 11:52 UTC, pelmegov commented on stock-system/src/main/java/saffchen/product/ReflectProductUtils.java
> +        } catch (IntrospectionException | IllegalAccessException | IllegalArgumentException | InvocationTargetException e) {
specify the parent exception?

2022-05-25 11:52 UTC, pelmegov commented on stock-system/src/main/java/saffchen/reports/PDFReportFromFile.java
> +        //List<Product> tableData = fileStorageUtils.getDataForReportBySatelliteFromCSV("Satellite", criteries);
It is better to remove comments when you are going to push changes

2022-05-25 11:59 UTC, pelmegov commented on stock-system/src/main/java/saffchen/utils/StorageUtils.java
> +    Connection I_CONNECTION = null;
Why do you need this field?

2022-05-25 12:08 UTC, freesky15 commented on stock-system/src/main/java/saffchen/reports/PDFReportFromFileBySatellite.java
> +            boolean isLight = true; //if background is light
Probably yes  but it will be as feature in the next realise.

2022-05-25 17:49 UTC, saffchen commented on stock-system/src/main/java/saffchen/command/CreateXlsFileCommand.java
> +        createXLS();
Fixed!

2022-05-26 10:24 UTC, pelmegov commented on stock-system/src/main/java/saffchen/command/CreateXlsFileCommand.java
> +        List <String> notAcceptSymbols = new ArrayList<>();
You can make it static: 
```
private static final List <String> DEPRECATED_SYMBOLS = List.of("/", "|");
```
And after just iterate through it: 
```
while (true) {
  System.out.println("Укажите название файла");
  System.out.println("Имя файла не должно содержать символы: " + DEPRECATED_SYMBOLS);
  String name = new Scanner(System.in).nextLine();
  if (isNameCorrect(name)) {
      break;
  }
}
```
And check method: 
```
private boolean isNameCorrect(String name) {
  for (String deprecatedSymbol: DEPRECATED_SYMBOLS) {
    if (name.contains(deprecatedSymbol)) {
        System.err.println("Ошибка, введите название корректно!");
        return false;
    }
  }
  return true;
}
```

2022-05-26 19:18 UTC, saffchen commented on stock-system/pom.xml
> -        <!-- https://mvnrepository.com/artifact/org.apache.pdfbox/pdfbox -->
We use itextpdf dependency.

2022-05-26 19:24 UTC, saffchen commented on stock-system/src/main/java/saffchen/command/ImportFromGSheetCommand.java
> +        receiverDB.importFromGsheet();
Receiver DB was incorrectly named initially. Now it has been renamed and has no relation to the database.  In the next releases we will finally move away from using this class.

2022-05-26 19:27 UTC, saffchen commented on stock-system/src/main/java/saffchen/reports/PDFReportFromFile.java
> +        //List<Product> tableData = fileStorageUtils.getDataForReportBySatelliteFromCSV("Satellite", criteries);
Fixed

2022-05-26 19:32 UTC, saffchen commented on stock-system/src/main/java/saffchen/command/Receiver.java
> +        fileStorageUtils.addProduct(new Product("Test record",
Test data has been deleted. Got here by accident.

2022-05-26 19:39 UTC, saffchen commented on stock-system/src/main/java/saffchen/command/CreateXlsFileCommand.java
> +        List <String> notAcceptSymbols = new ArrayList<>();
Fixed

2022-05-26 19:44 UTC, saffchen commented on stock-system/src/main/java/saffchen/product/ReflectProductUtils.java
> +        } catch (IntrospectionException | IllegalAccessException | IllegalArgumentException | InvocationTargetException e) {
Fixed

2022-05-27 11:08 UTC, freesky15 commented on stock-system/src/main/java/saffchen/command/GenerateReportCommand.java
> +            if (criteria.equals("EXIT"))
Done!

2022-05-27 11:09 UTC, freesky15 commented on stock-system/src/main/java/saffchen/utils/IStorageUtils.java
> +    IConnection I_CONNECTION = null;
It was deleting.

2022-05-27 11:09 UTC, freesky15 commented on stock-system/src/main/java/saffchen/utils/IStorageUtils.java
> +    IConnection I_CONNECTION = null;
Done!

2022-05-27 11:48 UTC, freesky15 commented on stock-system/src/main/java/saffchen/utils/StorageUtils.java
> +    Connection I_CONNECTION = null;
Deleted!
Done!

2022-05-27 15:27 UTC, pelmegov commented
@freesky15 did you push your latest changes ?

2022-05-27 15:45 UTC, pelmegov approved these changes
Good job guys.

2022-05-27 15:57 UTC, saffchen commented
> Good job guys. 

Thanks

2022-05-27 17:10 UTC, merged