JT-12 [getting participants from backend]
saffchen/JRM-Java-Stock-System pull request #49
Opened 2022-06-24 11:16 UTC by fstk1337

2022-06-24 17:22 UTC, pelmegov requested changes

2022-06-24 17:22 UTC, pelmegov commented on vue-app/src/components/footer/Footer.vue
> +      baseURL: 'http://localhost:8080',
Let's extract it to configuration file.

2022-06-24 17:22 UTC, pelmegov commented on vue-app/src/components/footer/Footer.vue
> +function getContributors(obj) {
Vue has a methods section, we can use it to put our methods there without passing the obj reference.

2022-06-24 17:22 UTC, pelmegov commented on stock-system/src/main/java/saffchen/controller/ParticipantController.java
> +        response.addHeader("Access-Control-Allow-Origin", "*");
It's better to separate business logic and infrastructure settings, let's try to find another and probably better way to allow origin.

2022-06-24 21:12 UTC, fstk1337 commented on vue-app/src/components/footer/Footer.vue
> +      baseURL: 'http://localhost:8080',
Done.

2022-06-24 21:12 UTC, fstk1337 commented on vue-app/src/components/footer/Footer.vue
> +function getContributors(obj) {
Done.

2022-06-24 21:12 UTC, fstk1337 commented on stock-system/src/main/java/saffchen/controller/ParticipantController.java
> +        response.addHeader("Access-Control-Allow-Origin", "*");
Done.

2022-06-25 07:23 UTC, saffchen approved these changes

2022-06-25 09:24 UTC, pelmegov commented on stock-system/src/main/java/saffchen/controller/ParticipantController.java
> +    public List<ParticipantDto> getParticipants(HttpServletResponse response) {
Let's remove unnecessary parameter.

2022-06-25 09:24 UTC, pelmegov approved these changes

2022-06-25 10:34 UTC, fstk1337 commented on stock-system/src/main/java/saffchen/controller/ParticipantController.java
> +    public List<ParticipantDto> getParticipants(HttpServletResponse response) {
Done.

2022-06-25 10:35 UTC, merged