Merge-RELEASE. Project 2. #1. Week 2
saffchen/JRM-Java-Stock-System pull request #53
Opened 2022-06-25 20:10 UTC by saffchen

2022-06-26 18:01 UTC, pelmegov requested changes

2022-06-26 18:28 UTC, saffchen commented on stock-system/src/main/java/saffchen/entities/SatelliteEntity.java
> +    private List<ProductEntity> product;
Fixed

2022-06-28 16:47 UTC, pelmegov commented
@fstk1337 could you please fix issues?

2022-06-29 08:18 UTC, fstk1337 commented
>

2022-06-29 13:15 UTC, fstk1337 commented
> @fstk1337 could you please fix issues?

Some fixes done.

2022-06-29 16:18 UTC, pelmegov approved these changes

2022-06-29 20:43 UTC, merged