Jt 15 create rest for satellite
saffchen/JRM-Java-Stock-System pull request #60
Opened 2022-07-09 13:37 UTC by saffchen

2022-07-09 13:42 UTC, saffchen commented on stock-system/src/main/java/saffchen/controller/satellite/SatelliteRestController.java
> +    @GetMapping("/all")
@freesky15, Please follow Best Practice in naming requests

2022-07-09 13:43 UTC, saffchen commented on stock-system/src/main/java/saffchen/controller/satellite/SatelliteRestController.java
> +        return satelliteService.findAll();
@freesky15, Should be returned ResponseEntity

2022-07-09 13:44 UTC, saffchen commented on stock-system/src/main/java/saffchen/controller/satellite/SatelliteRestController.java
> +    @GetMapping("/id/{id}")
@freesky15, same way naming

2022-07-09 13:44 UTC, saffchen commented on stock-system/src/main/java/saffchen/controller/satellite/SatelliteRestController.java
> +    @GetMapping("/name/{name}")
@freesky15, same way naming

2022-07-09 13:46 UTC, saffchen commented on stock-system/src/main/java/saffchen/service/SatelliteService.java
> +        satelliteDTO.setName(satelliteEntity.getName());
@freesky15, If we do not use this, then the commented out line should be removed

2022-07-09 13:53 UTC, pelmegov requested changes

2022-07-09 13:53 UTC, pelmegov commented on stock-system/src/main/java/saffchen/controller/satellite/SatelliteRestController.java
> +    @GetMapping("/all")
Let's remove /all, /id, /name from path. It's not a good practice in rest api.

2022-07-09 13:53 UTC, pelmegov commented on stock-system/src/main/java/saffchen/entities/ProductEntity.java
> -@Table(name = "Product")
Looks like correct formatting has been changed to incorrect one.

2022-07-09 13:53 UTC, pelmegov commented on stock-system/src/main/java/saffchen/entities/ProductEntity.java
> +    public boolean equals(Object o) {
Lombok can replace some trivial boilerplate.

2022-07-09 13:53 UTC, pelmegov commented on stock-system/src/main/java/saffchen/repositories/SatelliteRepository.java
> +    @Query("SELECT new saffchen.dto.SatelliteDTO(se.id, se.name, se.description, COUNT(p.id)) " +
It's not a best idea to map entity to the dto right here, let's do it outside of repository/dao layer.

2022-07-09 13:53 UTC, pelmegov commented on stock-system/src/main/java/saffchen/service/SatelliteService.java
> +    private SatelliteDTO convertToSatelliteDTO(SatelliteEntity satelliteEntity){
This is not a service level transformation and can be replaced by mapstruct.

2022-07-09 13:53 UTC, pelmegov commented on stock-system/src/main/java/saffchen/service/SatelliteService.java
> +    private EntityManager em;
I don't think that entity manager is required here.

2022-07-09 13:53 UTC, pelmegov commented on stock-system/src/main/java/saffchen/service/SatelliteService.java
> +            System.out.println(sdto.getId() + " : " + sdto.getName() + " : " + sdto.getDescription() + " : " + sdto.getCount());
We shouldn't use printing to console anywhere, let's use logger, but just for the valueable information - for troubleshooting or some critical sections logging.

2022-07-09 13:53 UTC, pelmegov commented on stock-system/src/main/java/saffchen/service/SatelliteService.java
> +@Transactional(readOnly = true)
Let's move the Transactional annotation to method level. We actually would like to store a new satellites later.

2022-07-09 13:53 UTC, pelmegov commented on stock-system/src/main/java/saffchen/service/SatelliteService.java
> +        Long convertedId = Long.valueOf(id);
Why do we need that transformation from Long to Long?

2022-07-09 13:53 UTC, pelmegov commented on stock-system/src/main/java/saffchen/service/SatelliteService.java
> +        return foundSatellite.orElse(null);
Minor: Let's group to method chain.

2022-07-09 13:53 UTC, pelmegov commented on stock-system/src/main/java/saffchen/utils/SatelliteExceptionResponce.java
> +public class SatelliteExceptionResponce {
Why do we need that class? Let's remove it or transform to exception like SatelliteNotFoundException or something like similar.

2022-07-09 13:56 UTC, saffchen commented on stock-system/src/main/java/saffchen/service/SatelliteService.java
> +import org.springframework.data.jpa.repository.Query;
minor: unused dependencies

2022-07-10 11:10 UTC, fstk1337 reviewed
Agreed with existing comments. Directory stock-system should be renamed to stock to be able to merge into dev.

2022-07-12 16:30 UTC, closed without merging