Refactoring
saffchen/JRM-Java-Stock-System pull request #82
Opened 2022-08-01 08:54 UTC by freesky15

2022-08-01 09:06 UTC, saffchen commented
Please order the task number

2022-08-01 18:11 UTC, saffchen commented on stock/src/main/java/saffchen/entities/PersonEntity.java
> +    //@Enumerated(value=EnumType.STRING)
If we don't need this annotation then delete it

2022-08-01 18:14 UTC, saffchen commented on stock/src/main/java/saffchen/entities/SatelliteEntity.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
Why was the previous generation version changed

2022-08-01 18:19 UTC, saffchen commented on stock/src/main/java/saffchen/entities/PersonEntity.java
> +public class PersonEntity {
Do we can use  other class name? Title "PersonEntity" not clear.

2022-08-01 18:21 UTC, saffchen requested changes

2022-08-01 18:21 UTC, saffchen commented on stock/src/main/java/saffchen/entities/PersonEntity.java
> +    //@Enumerated(value=EnumType.STRING)
If we don't need this annotation then delete it

2022-08-02 07:50 UTC, freesky15 commented on stock/src/main/java/saffchen/entities/PersonEntity.java
> +public class PersonEntity {
Sorry, I can't understand what do you mean?

2022-08-02 07:58 UTC, closed without merging

2022-08-02 08:01 UTC, freesky15 commented
The Branch was updated