Jt 26 add spring security
saffchen/JRM-Java-Stock-System pull request #88
Opened 2022-08-15 15:33 UTC by freesky15

Add spring security(jwt support)

2022-08-15 18:34 UTC, saffchen requested changes

2022-08-15 18:34 UTC, saffchen commented on stock/src/main/java/saffchen/controller/AuthController.java
> +    @PostMapping("/check_auth"
Why is this section of code commented out?

2022-08-15 18:36 UTC, saffchen commented on stock/src/main/java/saffchen/entities/PersonEntity.java
> +public class PersonEntity {
Can you rename this class? I think UserEntity would be a more appropriate name

2022-08-15 18:43 UTC, saffchen commented on stock/src/main/java/saffchen/controller/AuthController.java
> +    @RequestMapping(value = "/check_auth", method = RequestMethod.POST)
Why don't use @PostMapping?

2022-08-16 18:02 UTC, fstk1337 commented on stock/src/main/resources/data.sql
> +        (4, 'TEST TEST DESCRIPTION', 'testAdmin@email.ru', true, 'testAdmin testAdmin', '$2a$12$bn9d4i7rHBC0nh5gwViCs.weW7OUdZ0kFac2PbsIZA0o.mw9wj2sW', 'ROLE_ADMIN', 'testadmin');
Could you please share unencrypted passwords for each user?

2022-08-17 10:52 UTC, pelmegov requested changes

2022-08-17 10:52 UTC, pelmegov commented on stock/src/main/java/saffchen/config/SecurityConfig.java
> +        return new BCryptPasswordEncoder(12);
Why did you decide to use 12 rounds for BCrypt? Is it much better than default 10?

2022-08-17 10:52 UTC, pelmegov commented on stock/src/main/java/saffchen/config/SecurityConfig.java
> +    public SecurityConfig(PersonEntityDetailsService personEntityDetailsService, JWTSecurityFilter jwtSecurityFilter) {
Minor: Can be replaced with lombok.

2022-08-17 10:52 UTC, pelmegov commented on stock/src/main/java/saffchen/config/SecurityConfig.java
> +                .antMatchers(HttpMethod.POST,"/api/**").hasAuthority("ROLE_ADMIN")
Minor: mvc matchers have better usability.

2022-08-17 10:52 UTC, pelmegov commented on stock/src/main/java/saffchen/controller/AuthController.java
> +    public AuthController(JwtUtil jwtUtil, PersonEntityDetailsService personEntityDetailsService, AuthenticationManager authenticationManager) {
Minor: can be replaced by lombok.

2022-08-17 10:52 UTC, pelmegov commented on stock/src/main/java/saffchen/controller/AuthController.java
> +public class AuthController {
Minor: don't forget to autoformat code.

2022-08-17 10:52 UTC, pelmegov commented on stock/src/main/java/saffchen/controller/AuthController.java
> +    /*
Commented code should be removed.

2022-08-17 10:52 UTC, pelmegov commented on stock/src/main/java/saffchen/dto/PersonAuthRequest.java
> +    private String username;
Do we use email instead of username?

2022-08-17 10:52 UTC, pelmegov commented on stock/src/main/java/saffchen/controller/AuthController.java
> +@RestController
Does it make sense to put everything inside "/auth/**" path or similar? What do you think?

2022-08-17 10:52 UTC, pelmegov commented on stock/src/main/java/saffchen/dto/PersonAuthResponse.java
> +    public PersonAuthResponse(String jwt) {
Minor: lombok. If you use the latest java, it also can be replaced to https://docs.oracle.com/en/java/javase/18/language/records.html .

2022-08-17 10:52 UTC, pelmegov commented on stock/src/main/java/saffchen/security/JWTSecurityFilter.java
> +                    String username = jwtUtil.validateTockenAndGetClaim(onlyToken);
Minor: mistake Tocken -> Token

2022-08-17 10:52 UTC, pelmegov commented on stock/src/main/java/saffchen/security/JWTSecurityFilter.java
> +                    if (SecurityContextHolder.getContext().getAuthentication() == null){
You can probably wrap by this "if" the whole logic, because you assign the authToken only if authentication is null. So you don't need to do anything else in case when authentication already in security context.

2022-08-17 10:52 UTC, pelmegov commented on stock/src/main/java/saffchen/security/JwtUtil.java
> +public class JwtUtil {
Minor: autoformatting.

2022-08-17 10:52 UTC, pelmegov commented on stock/src/main/java/saffchen/security/JwtUtil.java
> +            JWTVerifier jwtVerifier = JWT.require(Algorithm.HMAC512(secret))
This verifier could be created only once and reused later multiple times, right?

2022-08-17 10:52 UTC, pelmegov commented on stock/src/main/java/saffchen/security/PersonDetails.java
> +    public PersonEntity getPersonEntity(){
I don't think you need this getter at all.

2022-08-17 10:52 UTC, pelmegov commented on stock/src/main/java/saffchen/service/PersonEntityDetailsService.java
> +@Service("personEntityDetailService")
Do we need qualifier here?

2022-08-17 10:52 UTC, pelmegov commented on stock/src/main/resources/application.properties
> +jwt.token.expired=60
It's in minutes/hours/days? Could you please add clarification here in comment may be.

2022-08-17 10:52 UTC, pelmegov commented on vue-app/src/components/header/Navbar.vue
> +<template xmlns="http://www.w3.org/1999/html">
Why do we need that "xmlns="http://www.w3.org/1999/html""?

2022-08-19 06:12 UTC, freesky15 commented on stock/src/main/java/saffchen/config/SecurityConfig.java
> +        return new BCryptPasswordEncoder(12);
if the password has more iterations then it more strongly

2022-08-19 06:18 UTC, freesky15 commented on stock/src/main/resources/data.sql
> +        (4, 'TEST TEST DESCRIPTION', 'testAdmin@email.ru', true, 'testAdmin testAdmin', '$2a$12$bn9d4i7rHBC0nh5gwViCs.weW7OUdZ0kFac2PbsIZA0o.mw9wj2sW', 'ROLE_ADMIN', 'testadmin');
Unencrypted password == last string of record, for example testAdmin@email.ru = testadmin

2022-08-19 06:19 UTC, freesky15 commented on stock/src/main/java/saffchen/controller/AuthController.java
> +    @PostMapping("/check_auth"
fixed

2022-08-19 07:34 UTC, freesky15 commented on stock/src/main/java/saffchen/config/SecurityConfig.java
> +        return new BCryptPasswordEncoder(12);
changed to 10

2022-08-22 04:51 UTC, freesky15 commented on stock/src/main/java/saffchen/controller/AuthController.java
> +    public AuthController(JwtUtil jwtUtil, PersonEntityDetailsService personEntityDetailsService, AuthenticationManager authenticationManager) {
fixed by @RequiredArgsConstructor annotation

2022-08-22 04:51 UTC, freesky15 commented on stock/src/main/java/saffchen/config/SecurityConfig.java
> +    public SecurityConfig(PersonEntityDetailsService personEntityDetailsService, JWTSecurityFilter jwtSecurityFilter) {
fixed by @RequiredArgsConstructor annotation

2022-08-22 04:51 UTC, freesky15 commented on stock/src/main/java/saffchen/controller/AuthController.java
> +public class AuthController {
fixed

2022-08-22 04:52 UTC, freesky15 commented on stock/src/main/java/saffchen/controller/AuthController.java
> +    /*
fixed

2022-08-22 04:59 UTC, freesky15 commented on stock/src/main/java/saffchen/security/JWTSecurityFilter.java
> +                    String username = jwtUtil.validateTockenAndGetClaim(onlyToken);
fixed

2022-08-22 05:14 UTC, freesky15 commented on stock/src/main/resources/application.properties
> +jwt.token.expired=60
added a comment

2022-08-22 05:15 UTC, freesky15 commented on stock/src/main/java/saffchen/service/PersonEntityDetailsService.java
> +@Service("personEntityDetailService")
i think no

2022-08-22 05:20 UTC, freesky15 commented on stock/src/main/java/saffchen/security/PersonDetails.java
> +    public PersonEntity getPersonEntity(){
I agree with you. Fixed

2022-08-22 05:38 UTC, freesky15 commented on stock/src/main/java/saffchen/dto/PersonAuthRequest.java
> +    private String username;
changed

2022-08-22 05:45 UTC, freesky15 commented on stock/src/main/java/saffchen/security/JwtUtil.java
> +public class JwtUtil {
fixet

2022-08-22 06:03 UTC, freesky15 commented on stock/src/main/java/saffchen/security/JWTSecurityFilter.java
> +                    if (SecurityContextHolder.getContext().getAuthentication() == null){
I agree with you. Fixed

2022-08-22 08:37 UTC, freesky15 commented on stock/src/main/java/saffchen/dto/PersonAuthResponse.java
> +    public PersonAuthResponse(String jwt) {
fixed

2022-08-22 08:53 UTC, freesky15 commented on stock/src/main/java/saffchen/controller/AuthController.java
> +    @RequestMapping(value = "/check_auth", method = RequestMethod.POST)
fixed

2022-08-23 09:21 UTC, freesky15 commented on stock/src/main/java/saffchen/config/SecurityConfig.java
> +                .antMatchers(HttpMethod.POST,"/api/**").hasAuthority("ROLE_ADMIN")
Fixed

2022-08-23 09:29 UTC, freesky15 commented on stock/src/main/java/saffchen/controller/AuthController.java
> +@RestController
fixed

2022-08-23 09:44 UTC, freesky15 commented on vue-app/src/components/header/Navbar.vue
> +<template xmlns="http://www.w3.org/1999/html">
deleted

2022-08-24 06:13 UTC, freesky15 commented on stock/src/main/java/saffchen/entities/PersonEntity.java
> +public class PersonEntity {
renamed

2022-08-24 06:14 UTC, saffchen approved these changes

2022-08-24 09:53 UTC, pelmegov requested changes

2022-08-24 09:53 UTC, pelmegov commented on stock/src/main/java/saffchen/repository/PersonsRepository.java
> +public interface PersonsRepository extends JpaRepository<UserEntity, Integer> {
Repository name, table name and entity name should be the same to avoid confusing.

2022-08-24 09:53 UTC, pelmegov commented on stock/src/main/java/saffchen/security/JWTSecurityFilter.java
> +        if (authHeader != null && !authHeader.isBlank() && authHeader.startsWith(prefix)) {
Minor: can be replaced to !StringUtils.isEmpty

2022-08-26 09:23 UTC, fstk1337 commented on vue-app/src/components/header/Navbar.vue
> +<template xmlns="http://www.w3.org/1999/html">
> deleted

Please, do not remove the tag, just the 'xmlns' attribute inside.

2022-08-26 10:14 UTC, freesky15 commented on stock/src/main/java/saffchen/security/JWTSecurityFilter.java
> +        if (authHeader != null && !authHeader.isBlank() && authHeader.startsWith(prefix)) {
But the !StringUtils.isEmpty from springframework.util.StringUtils is deprecated

2022-08-26 11:06 UTC, freesky15 commented on stock/src/main/java/saffchen/repository/PersonsRepository.java
> +public interface PersonsRepository extends JpaRepository<UserEntity, Integer> {
fixed

2022-08-26 11:06 UTC, freesky15 commented on stock/src/main/java/saffchen/security/JWTSecurityFilter.java
> +        if (authHeader != null && !authHeader.isBlank() && authHeader.startsWith(prefix)) {
changed

2022-08-26 12:00 UTC, pelmegov approved these changes

2022-08-26 12:01 UTC, merged